# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k24jMlO00LIirIvueTygWWHlo8tCN9Sk
"""

# plot_chart.py
import matplotlib.pyplot as plt
import numpy as np

# Generate example data
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Create a line plot
plt.plot(x, y, label='Sin(x)')
plt.title('Matplotlib Chart Example')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend()

# Save the plot as an image (optional)
plt.savefig('chart.png')

# Display the plot
plt.show()